apiVersion: v1
kind: Service
metadata:
  name: book-server
spec:
  selector:
    app: book-server
  ports:
    - protocol: TCP
      port: 8080       # Cluster-internal port
      targetPort: 3000  # Your Go server port
  type: ClusterIP
